apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-replica
  namespace: murali-ns
spec:
  replicas: 10
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank 
    spec:
       containers:
        - name: bank-app
          image: muralisocial123/bank:v1
          ports:
            - containerPort: 3000